"""add_owner_column

Revision ID: 40daddd85d36
Revises: b84341b575e8
Create Date: 2026-04-02 11:06:13.521090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40daddd85d36'
down_revision: Union[str, Sequence[str], None] = 'b84341b575e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('owner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'owner')
    # ### end Alembic commands ###
