"""link_cars_to_mechanics

Revision ID: 54f16970b3f3
Revises: 1f437f5cea8c
Create Date: 2026-04-07 12:50:34.823245

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54f16970b3f3"
down_revision: str | Sequence[str] | None = "1f437f5cea8c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cars", sa.Column("mechanic_username", sa.String(), nullable=False))
    op.create_foreign_key(None, "cars", "users", ["mechanic_username"], ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cars", type_="foreignkey")
    op.drop_column("cars", "mechanic_username")
    # ### end Alembic commands ###
