"""add index to brand

Revision ID: d60eda0ecc2e
Revises: 54f16970b3f3
Create Date: 2026-04-09 12:33:15.994363

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d60eda0ecc2e"
down_revision: Union[str, Sequence[str], None] = "54f16970b3f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_cars_brand"), "cars", ["brand"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cars_brand"), table_name="cars")
    # ### end Alembic commands ###
