from typing import Annotated, Any

from fastapi import APIRouter, Depends, status
from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession

from auth import get_db, require_admin
from models import ApiKeyDB

router = APIRouter(prefix="/api/v1/keys", tags=["API Keys"])


class ApiKeyCreate(BaseModel):
    owner_name: str = Field(..., min_length=2, description="Name of the partner company, e.g., 'Bolt Fleet'")


class ApiKeyResponse(BaseModel):
    key: str
    owner_name: str
    message: str


@router.post("/", status_code=status.HTTP_201_CREATED, response_model=ApiKeyResponse)
async def create_api_key(
    request: ApiKeyCreate,
    admin_user: Annotated[dict[str, Any], Depends(require_admin)],
    db: AsyncSession = Depends(get_db),
) -> Any:

    new_key = ApiKeyDB(owner_name=request.owner_name)

    db.add(new_key)
    await db.commit()
    await db.refresh(new_key)

    return ApiKeyResponse(
        key=new_key.key,
        owner_name=new_key.owner_name,
        message=f"API Key for {new_key.owner_name} has been successfully generated by {admin_user['username']}.",
    )
