name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd garage-management-api
            git pull origin main
            docker compose up -d --build
